# Generated by Django 4.0.2 on 2022-04-18 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userlikers',
            field=models.ManyToManyField(blank=True, related_name='userlikers', to=settings.AUTH_USER_MODEL),
        ),
    ]
