# Generated by Django 4.0.2 on 2022-03-06 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0004_alter_post_likes_alter_restaurant_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
